---
zabbix:
  user: username
  pass: password
  server: server
  https-verify: true

cachet:
  token: token
  server: server
  https-verify: true

settings:
  # SERVICES

  # IT Service which will be a root for Cachet Components
  # Leave it empty if you want to use /
  root_service: 'Saritasa'
  # IT Services, which SLA will be exported in Cachet metrics
  metric_services:
    'Resources'
    'Routers'

  # TIMING

  # How often check Zabbix for new incidents
  update_inc_interval: 10  # in seconds
  # How often check Zabbix for new IT Services
  update_comp_interval: 60  # in seconds
  # How often update metrics in Cachet
  update_metric_interval: 30

  # LOGGING

  # Log level https://docs.python.org/3.4/library/logging.html#levels
  log_level: INFO
  # Additional logging level for requests module
  log_level_requests: WARNING